version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    restart: unless-stopped

  test:
    build:
      context: .
      dockerfile: Dockerfile  
    command: ["pytest", "test_app.py"]
    depends_on:
      - app
    volumes:
      - .:/app