version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile  # Especificar el Dockerfile si tiene un nombre diferente
    command: ["pytest", "test_app.py"]
    depends_on:
      - app                    # Asegurar que el servicio de app esté disponible
    volumes:
      - .:/app
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Especificar el Dockerfile si tiene un nombre diferente
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    restart: unless-stopped    # Reiniciar el contenedor a menos que se detenga manualmente
