name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "asantillan" --password-stdin

      - name: Build and tag Docker image
        run: |
          docker build -t asantillan/up-devops-backend:latest .

      - name: Push Docker image to DockerHub
        run: |
          docker push asantillan/up-devops-backend:latest

      - name: Trigger Render Deploy Hook
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
