name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

permissions:
  id-token: write   
  contents: read    

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::563935605077:role/github-actions-role

      - name: Build Docker image
        run: |
          docker build -t develop .

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 563935605077.dkr.ecr.us-east-1.amazonaws.com

      - name: Tag Docker image
        run: |
          docker tag develop 563935605077.dkr.ecr.us-east-1.amazonaws.com/up-devops-webapp:develop

      - name: Push Docker image
        run: |
          docker push 563935605077.dkr.ecr.us-east-1.amazonaws.com/up-devops-webapp:develop

  #deploy:
  #  runs-on: ubuntu-latest
  #  needs: push
  #  if: success()
  #  steps:
  #    - name: Configure AWS Credentials
  #      uses: aws-actions/configure-aws-credentials@v4
  #      with:
  #        aws-region: us-east-1
  #        role-to-assume: arn:aws:iam::563935605077:role/github-actions-role
  #
  #    - name: Create a CodeDeploy Deployment
  #      run: |
  #        aws deploy create-deployment \
  #          --application-name up_devops_backend \
  #          --deployment-group-name up_devops_deployment_group \
  #          --s3-location bucket=up-devops-codedeploy-tools,key=app_bundle.zip,bundleType=zip \
  #          --file-exists-behavior OVERWRITE